version: "3.8"
services:
  mysql:
    build: mysql
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql
  python:
    build: http-server
    image: python:3-alpine
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    
volumes:
  mysql-data: